//! Extract the runnable Rust snippets from the website into a doctest module.
//!
//! The README is already a doctest — `lib.rs` includes it under `cfg(doctest)` — but the
//! website was not covered by anything, and a guide whose first code block does not
//! compile is worse than no guide. This turns every ```` ```rust ```` block in
//! `site/content/**.md` that is not marked `ignore` into a doctest in
//! `src/site_doctests.rs`, so the same `cargo test` that checks everything else checks
//! the documentation a reader actually starts from.
//!
//! It lives in `src/` rather than `tests/` because rustdoc only collects doctests from the
//! library. `ignore` means what it means to rustdoc: rendered, not run.

use std::fmt::Write as _;
use std::path::Path;

/// Pull every non-`ignore` Rust block out of the site and write the doctest file.
pub fn generate(root: &Path) -> std::io::Result<usize> {
    let mut blocks: Vec<(String, usize, String)> = Vec::new();
    collect(&root.join("site/content"), root, &mut blocks)?;
    blocks.sort();

    let mut out = String::from(
        "//! The website's code blocks, as doctests.\n\
         //!\n\
         //! Generated by `cargo xtask gen-site-examples` from `site/content/**/*.md` — do\n\
         //! not edit. Every ```` ```rust ```` block on the website that is not marked\n\
         //! `ignore` appears here, so a guide cannot drift away from the API it teaches.\n\
         //! Fix the Markdown, then re-run the generator.\n\
         //!\n\
         //! The module is `cfg(doctest)`, so it costs a normal build nothing: rustdoc is\n\
         //! the only thing that ever compiles it.\n\n\
         // Each carrier is named after the file and block it came from, so a failure names\n\
         // the Markdown to fix. That is worth more here than the casing convention.\n\
         #![allow(non_camel_case_types)]\n\n",
    );
    for (path, index, body) in &blocks {
        let name = path
            .replace(['/', '.', '-'], "_")
            .trim_start_matches('_')
            .to_string();
        let _ = write!(
            out,
            "/// From [`{path}`], block {index}.\n\
             ///\n\
             /// ```\n"
        );
        for line in body.lines() {
            if line.is_empty() {
                out.push_str("///\n");
            } else {
                let _ = writeln!(out, "/// {line}");
            }
        }
        let _ = write!(
            out,
            "/// ```\n\
             #[allow(non_snake_case, dead_code)]\n\
             struct {name}_{index};\n\n"
        );
    }

    // rustfmt collapses a trailing blank line; emitting one would make `cargo fmt --check`
    // fail on a file the generator had just written.
    while out.ends_with("\n\n") {
        out.pop();
    }
    std::fs::write(root.join("src/site_doctests.rs"), out)?;
    Ok(blocks.len())
}

fn collect(dir: &Path, root: &Path, out: &mut Vec<(String, usize, String)>) -> std::io::Result<()> {
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            // The generated reference pages carry no hand-written code.
            if path.file_name().is_some_and(|n| n == "model") {
                continue;
            }
            collect(&path, root, out)?;
        } else if path.extension().is_some_and(|e| e == "md") {
            let text = std::fs::read_to_string(&path)?;
            let relative = path
                .strip_prefix(root)
                .unwrap_or(&path)
                .to_string_lossy()
                .into_owned();
            for (index, (flags, body)) in rust_blocks(&text).into_iter().enumerate() {
                // `ignore` means the same thing here as it does to rustdoc: rendered,
                // not run, because it needs something this test harness has not got.
                if flags.contains("ignore") || flags.contains("no_run") {
                    continue;
                }
                out.push((relative.clone(), index, body));
            }
        }
    }
    Ok(())
}

/// Every fenced block whose info string starts with `rust`, as `(flags, body)`.
fn rust_blocks(text: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut lines = text.lines();
    while let Some(line) = lines.next() {
        let Some(info) = line.trim_start().strip_prefix("```") else {
            continue;
        };
        if !info.starts_with("rust") {
            continue;
        }
        let flags = info.to_string();
        let mut body = String::new();
        for line in lines.by_ref() {
            if line.trim_start().starts_with("```") {
                break;
            }
            body.push_str(line);
            body.push('\n');
        }
        out.push((flags, body));
    }
    out
}
