//! Pairing as a state machine that refuses to advance when a rule is broken.
//!
//! The exchange is a **two-way** challenge–response, and the two directions are not
//! symmetrical in time: the client challenges first and the server answers in the same
//! round trip, then the server's challenge is answered one request later. Getting that
//! order wrong produces something that looks like authentication and proves nothing.
//!
//! ```text
//!   HTTPS client                                      HTTPS server
//!   ────────────                                      ────────────
//!   1. generate C_c
//!      POST /v1/requestPairing ───────────────────▶   2. R_c = HMAC(C_c, T ‖ binding)
//!         clientNodeDescription, C_c,                    (rate-limited, ≥ 1 s delay)
//!         versions, protocols, algorithms                generate C_s, attempt id
//!   4. check R_c                ◀───────────────────3. pairingAttemptId, R_c, C_s,
//!   5. R_s = HMAC(C_s, T ‖ binding)                     serverNodeDescription
//!   6A. POST /v1/requestConnectionDetails ───────▶   7A. check R_s
//!          R_s                  ◀───────────────────    ConnectionDetails
//!    or
//!   6B. POST /v1/postConnectionDetails ──────────▶   7B. check R_s
//!          R_s, ConnectionDetails
//!   8. POST /v1/finalizePairing {success} ───────▶   both sides store the pairing
//! ```
//!
//! Which of 6A and 6B applies is decided by [`Deployment::communication_server`], not by
//! preference: the side that will be the *communication* server is the side that has
//! connection details to give.
//!
//! `R_c` proves the server holds the pairing token **and** that the TLS identity answering
//! is the one the token was meant for — its leaf-certificate fingerprint in a LAN, its
//! domain name otherwise. `R_s` proves the client holds the token. Steps 2 through 8 are
//! authenticated by the `pairingAttemptId` the server issues, which is a bearer token.

use alloc::collections::BTreeMap;
use alloc::string::String;
use alloc::vec::Vec;

use serde::{Deserialize, Serialize};
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::types::{Duration, ProtocolVersion, Timestamp};

use super::{
    AccessToken, ChallengeResponse, CommunicationProtocol, ConnectError, Deployment,
    EndpointDescription, HmacBinding, HmacHashingAlgorithm, NodeDescription, NodeId, NodeIdAlias,
    PairingToken, Role,
};

/// How long a whole pairing attempt may take.
///
/// `S2C §Pairing`: "the pairing attempt must be finished within 15 seconds". Each side
/// keeps its own budget, because each side can only see its own clock.
pub const PAIRING_BUDGET: Duration = Duration::from_secs(15);

/// The delay the server must insert before answering `requestPairing`.
///
/// `S2C §2. Calculate clientHmacChallengeResponse`: "To mitigate brute-force attacks, the
/// server **must** enforce a mandatory delay of one second before sending its response to
/// the client. For any given node at the server, pairing attempts **must** be handled
/// sequentially, such that each second only one pairing attempt can be processed for a
/// node."
pub const MINIMUM_SERVER_DELAY: Duration = Duration::from_secs(1);

// ---------------------------------------------------------------------------
// Wire types — `s2-connect-pairing.yml`
// ---------------------------------------------------------------------------

/// The bearer token that authenticates steps 6 through 8 of one pairing attempt.
///
/// `S2C-OAS pairing/PairingAttemptId`: "a random string with a minimal length of 32
/// characters… generated by a cryptographically secure pseudorandom number generator. The
/// recommended method is to generate 24 random bytes and Base64 encode them."
#[derive(Clone, Zeroize, ZeroizeOnDrop, Serialize, Deserialize)]
#[serde(transparent)]
pub struct PairingAttemptId(String);

impl PairingAttemptId {
    /// The fewest characters the specification allows.
    pub const MIN_LEN: usize = 32;

    /// Wrap an identifier received from a peer.
    #[must_use]
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Generate one from the recommended 24 bytes of entropy.
    pub fn from_entropy(bytes: &[u8]) -> Result<Self, ConnectError> {
        // 24 bytes Base64-encode to exactly the 32 characters the minimum requires.
        if bytes.len() < 24 {
            return Err(ConnectError::WeakSecret {
                got: bytes.len(),
                need: 24,
            });
        }
        Ok(Self(super::base64_encode(bytes)))
    }

    /// The string, which is what travels in `Authorization: Bearer …`.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Whether a presented identifier is this one, compared in constant time.
    #[must_use]
    pub fn verify(&self, presented: &str) -> bool {
        use subtle::ConstantTimeEq as _;
        self.0.len() == presented.len() && bool::from(self.0.as_bytes().ct_eq(presented.as_bytes()))
    }
}

impl core::fmt::Debug for PairingAttemptId {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("PairingAttemptId(<redacted>)")
    }
}

/// The body of `POST /v1/requestPairing`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PairingRequest {
    /// Who the client is.
    pub client_node_description: NodeDescription,
    /// Where the client's endpoint runs.
    pub client_endpoint_description: EndpointDescription,
    /// Which node at the endpoint, when the client knows its identifier.
    ///
    /// `S2C-OAS pairing/requestPairing`: "The (optional) properties nodeId and nodeIdAlias
    /// may never be used at the same time." [`PairingClient`] cannot set both.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
    /// Which node at the endpoint, when the client only has the alias from the code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub node_id_alias: Option<NodeIdAlias>,
    /// How the client can carry S2 messages afterwards.
    pub supported_communication_protocols: Vec<CommunicationProtocol>,
    /// **S2 JSON** message versions — the same versions the `Handshake` negotiates,
    /// spelled the way `S2C` spells them (E25).
    pub supported_s2_message_versions: Vec<ProtocolVersion>,
    /// The hash functions the client accepts; SHA-256 "**must** be present".
    pub supported_hmac_hashing_algorithms: Vec<HmacHashingAlgorithm>,
    /// `C_c`: a nonce of at least 32 bytes, Base64.
    pub client_hmac_challenge: String,
    /// Pair anyway, even with no S2 message version in common.
    #[serde(default, skip_serializing_if = "core::ops::Not::not")]
    pub force_pairing: bool,
}

/// The `200` body of `requestPairing`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PairingAccepted {
    /// The bearer for the rest of the attempt.
    pub pairing_attempt_id: PairingAttemptId,
    /// Who the server is.
    pub server_node_description: NodeDescription,
    /// Where the server's endpoint runs.
    pub server_endpoint_description: EndpointDescription,
    /// The hash function the server chose from the client's list.
    pub selected_hmac_hashing_algorithm: HmacHashingAlgorithm,
    /// `R_c`: the server's answer to the client's challenge.
    pub client_hmac_challenge_response: String,
    /// `C_s`: the server's own nonce.
    pub server_hmac_challenge: String,
}

/// Why a pairing was refused. `S2C-OAS pairing/PairingResponseErrorMessage`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum PairingErrorMessage {
    /// Two CEMs, or two RMs.
    InvalidCombinationOfRoles,
    /// No S2 JSON message version in common.
    IncompatibleS2MessageVersions,
    /// No hash function in common.
    IncompatibleHmacHashingAlgorithms,
    /// No transport in common.
    IncompatibleCommunicationProtocols,
    /// The alias or identifier names no node here.
    NodeNotFound,
    /// The endpoint hosts more than one node and the client named none.
    NoNodeIdProvided,
    /// No pairing token is active for that node.
    NoValidPairingTokenOnPairingServer,
    /// The body was not understood.
    ParsingError,
    /// Anything else.
    Other,
}

/// The `400` body of `requestPairing`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PairingRefused {
    /// Which of the enumerated reasons.
    pub error_message: PairingErrorMessage,
    /// Free text, for a log.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_info: Option<String>,
}

/// Where a communication client should connect, and with what.
///
/// `S2C-OAS pairing/ConnectionDetails`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConnectionDetails {
    /// The base URL of the session-initiation API.
    pub initiate_session_url: String,
    /// The first access token, which session initiation will rotate.
    pub access_token: AccessToken,
    /// Fingerprints of the **CA** certificate the communication server uses, by hashing
    /// algorithm; `SHA256` is always present.
    ///
    /// Note that this is the *CA*, whereas the HMAC binding uses the **leaf**
    /// (`S2C §Challenge response process`). They are different certificates and the
    /// specification names them differently in the two places; conflating them produces a
    /// pairing that verifies and a connection that does not.
    ///
    /// "Mandatory when the pairing client will become the communication server."
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub certificate_fingerprint: BTreeMap<String, String>,
}

/// The body of `requestConnectionDetails` (6A).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConnectionDetailsRequest {
    /// `R_s`: the client's answer to the server's challenge.
    pub server_hmac_challenge_response: String,
}

/// The body of `postConnectionDetails` (6B).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConnectionDetailsPost {
    /// `R_s`: the client's answer to the server's challenge.
    pub server_hmac_challenge_response: String,
    /// What the client, as the future communication server, is offering.
    pub connection_details: ConnectionDetails,
}

/// The body of `finalizePairing` (8).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct FinalizePairing {
    /// Whether the client is satisfied and has stored the pairing.
    pub success: bool,
}

/// A completed pairing, ready to be stored.
#[derive(Debug, Clone)]
pub struct Pairing {
    /// This node.
    pub local: NodeId,
    /// The node paired with.
    pub remote: NodeDescription,
    /// The remote endpoint.
    pub remote_endpoint: EndpointDescription,
    /// Where to initiate sessions, and with what.
    pub details: ConnectionDetails,
    /// Which side will be the communication server.
    pub communication_server: Role,
    /// The S2 JSON message versions both sides offered, newest first — what a later
    /// `Handshake` or `initiateSession` negotiates from.
    pub s2_message_versions: Vec<ProtocolVersion>,
}

// ---------------------------------------------------------------------------
// The client
// ---------------------------------------------------------------------------

/// How far a pairing attempt has got.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PairingStep {
    /// Nothing has been sent.
    Start,
    /// `requestPairing` has been sent; the server's answer has not arrived.
    AwaitingAcceptance,
    /// `R_c` is verified; connection details have not been exchanged.
    Authenticated,
    /// Connection details are known; `finalizePairing` has not been sent.
    DetailsExchanged,
    /// The pairing is complete and may be stored.
    Paired,
    /// The attempt failed and may not be resumed.
    Failed,
}

impl PairingStep {
    const fn name(self) -> &'static str {
        match self {
            PairingStep::Start => "the start of pairing",
            PairingStep::AwaitingAcceptance => "the server's acceptance",
            PairingStep::Authenticated => "connection details",
            PairingStep::DetailsExchanged => "finalization",
            PairingStep::Paired => "a completed pairing",
            PairingStep::Failed => "a failed pairing",
        }
    }
}

/// Which of steps 6A and 6B the client must take next.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NextStep {
    /// 6A — the pairing server will be the communication server, so ask it for details.
    RequestConnectionDetails,
    /// 6B — the pairing *client* will be the communication server, so send details.
    PostConnectionDetails,
}

/// The pairing client: the side that types in the code and makes the HTTPS requests.
///
/// ```
/// # use s2_kit::connect::proto::*;
/// # use s2_kit::types::Timestamp;
/// # fn me() -> NodeDescription { NodeDescription {
/// #   id: NodeId::parse("cem-1").unwrap(), brand: "Acme".into(), logo_url: None,
/// #   kind: "CEM".into(), model_name: "Hub".into(), user_defined_name: None,
/// #   role: Role::Cem } }
/// let code = PairingCode::parse("evse7-A1b2C3", TokenKind::Static)?;
/// let now = Timestamp::from_unix(1_700_000_000, 0);
///
/// let mut client = PairingClient::start(me(), EndpointDescription::default(), code, now);
/// let body = client.request_pairing(&[0xA5; 32])?;
/// assert_eq!(client.step(), PairingStep::AwaitingAcceptance);
/// // The alias from the code names the node; `nodeId` stays unset, as the spec requires.
/// assert!(body.node_id.is_none());
/// assert_eq!(body.node_id_alias.as_ref().unwrap().0, "evse7");
/// # Ok::<(), Box<dyn core::error::Error>>(())
/// ```
#[derive(Debug)]
pub struct PairingClient {
    local: NodeDescription,
    local_endpoint: EndpointDescription,
    code: super::PairingCode,
    /// Known only once the server has presented a certificate, which is why it arrives
    /// with [`PairingClient::accept`] rather than at the start.
    binding: Option<HmacBinding>,
    started: Timestamp,
    step: PairingStep,
    /// `C_c`, kept so the server's `R_c` can be checked against it in step 4.
    challenge: Option<Vec<u8>>,
    s2_message_versions: Vec<ProtocolVersion>,
    protocols: Vec<CommunicationProtocol>,
    force: bool,
    accepted: Option<PairingAccepted>,
    details: Option<ConnectionDetails>,
    communication_server: Option<Role>,
}

impl PairingClient {
    /// Begin an attempt. The fifteen-second clock starts here.
    #[must_use]
    pub fn start(
        local: NodeDescription,
        local_endpoint: EndpointDescription,
        code: super::PairingCode,
        now: Timestamp,
    ) -> Self {
        Self {
            local,
            local_endpoint,
            code,
            binding: None,
            started: now,
            step: PairingStep::Start,
            challenge: None,
            // Both, newest first — the deployed ecosystem still negotiates the beta.
            s2_message_versions: alloc::vec![
                crate::types::WireProfile::V1_0_0.connect_version(),
                crate::types::WireProfile::V0_0_2Beta.connect_version(),
            ],
            protocols: alloc::vec![CommunicationProtocol::WebSocket],
            force: false,
            accepted: None,
            details: None,
            communication_server: None,
        }
    }

    /// Offer a different set of S2 JSON message versions, newest first.
    #[must_use]
    pub fn with_s2_message_versions(mut self, versions: Vec<ProtocolVersion>) -> Self {
        self.s2_message_versions = versions;
        self
    }

    /// Pair even with no S2 message version in common.
    ///
    /// The two nodes will not be able to talk until one of them is updated, which is
    /// exactly what the flag is for: `S2C-OAS pairing` calls it out as something "could
    /// later be solved through a software update".
    #[must_use]
    pub fn forcing(mut self) -> Self {
        self.force = true;
        self
    }

    /// How far the attempt has got.
    #[must_use]
    pub const fn step(&self) -> PairingStep {
        self.step
    }

    /// The bearer for steps 6 through 8, once the server has issued one.
    #[must_use]
    pub fn attempt_id(&self) -> Option<&PairingAttemptId> {
        self.accepted.as_ref().map(|a| &a.pairing_attempt_id)
    }

    /// Step 1: build `requestPairing` from 32 bytes of cryptographically secure
    /// randomness.
    ///
    /// The randomness is a parameter because this layer has no business drawing it: a
    /// test needs it pinned, and a driver knows where the system's entropy lives.
    pub fn request_pairing(&mut self, challenge: &[u8]) -> Result<PairingRequest, ConnectError> {
        self.expect(PairingStep::Start)?;
        if challenge.len() < 32 {
            self.step = PairingStep::Failed;
            return Err(ConnectError::WeakSecret {
                got: challenge.len(),
                need: 32,
            });
        }
        self.challenge = Some(challenge.to_vec());
        self.step = PairingStep::AwaitingAcceptance;
        Ok(PairingRequest {
            client_node_description: self.local.clone(),
            client_endpoint_description: self.local_endpoint.clone(),
            // "may never be used at the same time" — the alias wins, because it is what
            // the user typed.
            node_id: None,
            node_id_alias: self.code.alias.clone(),
            supported_communication_protocols: self.protocols.clone(),
            supported_s2_message_versions: self.s2_message_versions.clone(),
            supported_hmac_hashing_algorithms: alloc::vec![HmacHashingAlgorithm::Sha256],
            client_hmac_challenge: super::base64_encode(challenge),
            force_pairing: self.force,
        })
    }

    /// Step 4: check `clientHmacChallengeResponse`, and decide which of 6A and 6B follows.
    ///
    /// This is the moment the client learns it is talking to something that holds the same
    /// pairing token *and* is the TLS identity the token was meant for. A man in the
    /// middle who terminates TLS with his own certificate computes a different `R_c` and
    /// is refused here.
    ///
    /// `S2C §4`: "in case of a local server, the TLS certificate fingerprint is part of
    /// the challenge. So if the challenge succeeds, the certificate fingerprint is
    /// correct, and the certificate can be trusted. The client **must** pin the
    /// self-signed CA (root) certificate."
    pub fn accept(
        &mut self,
        accepted: PairingAccepted,
        binding: HmacBinding,
        local_deployment: Deployment,
        now: Timestamp,
    ) -> Result<NextStep, ConnectError> {
        self.expect(PairingStep::AwaitingAcceptance)?;
        self.within_budget(now)?;
        self.binding = Some(binding);

        if !self
            .local
            .role
            .can_pair_with(accepted.server_node_description.role)
        {
            self.step = PairingStep::Failed;
            return Err(ConnectError::SameRole(self.local.role));
        }

        let challenge = self.challenge.as_ref().ok_or(ConnectError::OutOfOrder {
            got: "the server's acceptance",
            expected: "the start of pairing",
        })?;
        let binding = self.binding.as_ref().ok_or(ConnectError::ChallengeFailed)?;
        let expected = ChallengeResponse::compute(challenge, &self.code.token, binding)?;
        if !expected.verify(&accepted.client_hmac_challenge_response) {
            self.step = PairingStep::Failed;
            return Err(ConnectError::ChallengeFailed);
        }

        // Which side is the communication server is decided by the two deployments and
        // the two roles, never by preference.
        let server_deployment = accepted
            .server_endpoint_description
            .deployment
            .unwrap_or(Deployment::Lan);
        let (cem, rm) = if self.local.role == Role::Cem {
            (local_deployment, server_deployment)
        } else {
            (server_deployment, local_deployment)
        };
        let communication_server = Deployment::communication_server(cem, rm);
        self.communication_server = Some(communication_server);

        self.accepted = Some(accepted);
        self.step = PairingStep::Authenticated;
        Ok(if communication_server == self.local.role {
            NextStep::PostConnectionDetails
        } else {
            NextStep::RequestConnectionDetails
        })
    }

    /// Step 5: `R_s`, the answer to the server's challenge, Base64.
    ///
    /// Goes in the body of whichever of 6A and 6B [`Self::accept`] selected.
    pub fn server_challenge_response(&self) -> Result<String, ConnectError> {
        let accepted = self.accepted.as_ref().ok_or(ConnectError::OutOfOrder {
            got: "a challenge response",
            expected: "the server's acceptance",
        })?;
        let binding = self.binding.as_ref().ok_or(ConnectError::OutOfOrder {
            got: "a challenge response",
            expected: "the server's acceptance",
        })?;
        let challenge = super::base64_decode(&accepted.server_hmac_challenge)
            .ok_or(ConnectError::ChallengeFailed)?;
        Ok(ChallengeResponse::compute(&challenge, &self.code.token, binding)?.as_base64())
    }

    /// Step 6A: the body to send when the pairing server is the communication server.
    pub fn request_connection_details(&self) -> Result<ConnectionDetailsRequest, ConnectError> {
        Ok(ConnectionDetailsRequest {
            server_hmac_challenge_response: self.server_challenge_response()?,
        })
    }

    /// Step 6B: the body to send when *this* node is the communication server.
    pub fn post_connection_details(
        &mut self,
        details: ConnectionDetails,
        now: Timestamp,
    ) -> Result<ConnectionDetailsPost, ConnectError> {
        let response = self.server_challenge_response()?;
        self.connection_details(details.clone(), now)?;
        Ok(ConnectionDetailsPost {
            server_hmac_challenge_response: response,
            connection_details: details,
        })
    }

    /// Record the connection details, however they arrived.
    pub fn connection_details(
        &mut self,
        details: ConnectionDetails,
        now: Timestamp,
    ) -> Result<(), ConnectError> {
        self.expect(PairingStep::Authenticated)?;
        self.within_budget(now)?;
        self.details = Some(details);
        self.step = PairingStep::DetailsExchanged;
        Ok(())
    }

    /// Step 8: the body of `finalizePairing`, and the pairing to store.
    pub fn finalize(&mut self, now: Timestamp) -> Result<(FinalizePairing, Pairing), ConnectError> {
        self.expect(PairingStep::DetailsExchanged)?;
        self.within_budget(now)?;
        let accepted = self.accepted.take().ok_or(ConnectError::OutOfOrder {
            got: "finalization",
            expected: "the server's acceptance",
        })?;
        let details = self.details.take().ok_or(ConnectError::OutOfOrder {
            got: "finalization",
            expected: "connection details",
        })?;
        self.step = PairingStep::Paired;
        Ok((
            FinalizePairing { success: true },
            Pairing {
                local: self.local.id,
                remote: accepted.server_node_description,
                remote_endpoint: accepted.server_endpoint_description,
                details,
                communication_server: self.communication_server.unwrap_or(Role::Cem),
                s2_message_versions: self.s2_message_versions.clone(),
            },
        ))
    }

    /// Give up, telling the server so. `S2C §8`: the client may finalize with
    /// `success: false` "to let the server know it was not satisfied".
    pub fn abandon(&mut self) -> FinalizePairing {
        self.step = PairingStep::Failed;
        FinalizePairing { success: false }
    }

    fn expect(&mut self, step: PairingStep) -> Result<(), ConnectError> {
        if self.step == step {
            return Ok(());
        }
        let got = self.step.name();
        self.step = PairingStep::Failed;
        Err(ConnectError::OutOfOrder {
            got,
            expected: step.name(),
        })
    }

    fn within_budget(&mut self, now: Timestamp) -> Result<(), ConnectError> {
        if now.saturating_duration_since(self.started) > PAIRING_BUDGET {
            self.step = PairingStep::Failed;
            return Err(ConnectError::Expired {
                what: "pairing",
                limit: PAIRING_BUDGET,
            });
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// The server
// ---------------------------------------------------------------------------

/// The pairing server: the side that holds the token and answers.
///
/// It carries the two rules a request handler tends to lose — one attempt per node per
/// second, and a response delayed by at least a second — as state rather than as
/// discipline. `s2energy`'s S2 Connect layer has exactly these as an open issue.
#[derive(Debug)]
pub struct PairingServer {
    local: NodeDescription,
    local_endpoint: EndpointDescription,
    binding: HmacBinding,
    s2_message_versions: Vec<ProtocolVersion>,
    protocols: Vec<CommunicationProtocol>,
    /// The attempt currently in flight, if any.
    attempt: Option<Attempt>,
    /// When the last attempt for this node finished, for the rate limit.
    last_finished: Option<Timestamp>,
    /// The answer we owe the client, held until the mandatory second has elapsed.
    pending: Option<(Timestamp, PairingAccepted)>,
}

#[derive(Debug)]
struct Attempt {
    id: PairingAttemptId,
    started: Timestamp,
    /// `C_s`, kept so the client's `R_s` can be checked against it.
    expected_response: ChallengeResponse,
    client: NodeDescription,
    client_endpoint: EndpointDescription,
    s2_message_versions: Vec<ProtocolVersion>,
    details: Option<ConnectionDetails>,
    verified: bool,
}

impl PairingServer {
    /// A server for one node, bound to the identity clients will verify against.
    #[must_use]
    pub fn new(
        local: NodeDescription,
        local_endpoint: EndpointDescription,
        binding: HmacBinding,
    ) -> Self {
        Self {
            local,
            local_endpoint,
            binding,
            s2_message_versions: alloc::vec![
                crate::types::WireProfile::V1_0_0.connect_version(),
                crate::types::WireProfile::V0_0_2Beta.connect_version(),
            ],
            protocols: alloc::vec![CommunicationProtocol::WebSocket],
            attempt: None,
            last_finished: None,
            pending: None,
        }
    }

    /// Offer a different set of S2 JSON message versions, newest first.
    #[must_use]
    pub fn with_s2_message_versions(mut self, versions: Vec<ProtocolVersion>) -> Self {
        self.s2_message_versions = versions;
        self
    }

    /// Steps 2 and 3: handle `requestPairing`.
    ///
    /// Returns the `200` body **and the instant before which it may not be sent**. The
    /// delay is not advisory: with a four-character token there are 14.7 million
    /// possibilities, and one guess per second is the difference between a brute force
    /// taking months and taking an afternoon.
    ///
    /// A refusal consumes the rate-limit slot just as a success does, which is what makes
    /// the limit worth anything.
    ///
    /// # Errors
    ///
    /// [`ConnectError::RateLimited`] should become `503`; a [`PairingRefused`] carried in
    /// [`ConnectError::Refused`] should become `400` with that body.
    pub fn request_pairing(
        &mut self,
        request: &PairingRequest,
        token: &PairingToken,
        server_challenge: &[u8],
        attempt_id: PairingAttemptId,
        now: Timestamp,
    ) -> Result<(Timestamp, PairingAccepted), ConnectError> {
        if let Some(attempt) = &self.attempt
            && now.saturating_duration_since(attempt.started) <= PAIRING_BUDGET
        {
            return Err(ConnectError::RateLimited);
        }
        if let Some(finished) = self.last_finished
            && now.saturating_duration_since(finished) < MINIMUM_SERVER_DELAY
        {
            return Err(ConnectError::RateLimited);
        }

        let result = self.answer(request, token, server_challenge, attempt_id, now);
        if result.is_err() {
            self.last_finished = Some(now);
            self.attempt = None;
        }
        result
    }

    fn answer(
        &mut self,
        request: &PairingRequest,
        token: &PairingToken,
        server_challenge: &[u8],
        attempt_id: PairingAttemptId,
        now: Timestamp,
    ) -> Result<(Timestamp, PairingAccepted), ConnectError> {
        use PairingErrorMessage as E;

        // The checks in the order `S2C §1. Request pairing` tabulates them.
        if !self
            .local
            .role
            .can_pair_with(request.client_node_description.role)
        {
            return Err(refused(E::InvalidCombinationOfRoles));
        }
        if !request
            .supported_hmac_hashing_algorithms
            .contains(&HmacHashingAlgorithm::Sha256)
        {
            return Err(refused(E::IncompatibleHmacHashingAlgorithms));
        }
        if !request
            .supported_communication_protocols
            .iter()
            .any(|p| self.protocols.contains(p))
        {
            return Err(refused(E::IncompatibleCommunicationProtocols));
        }
        // A version mismatch is refusable, but `forcePairing` overrides it: the nodes
        // pair now and talk after a software update.
        let common = request
            .supported_s2_message_versions
            .iter()
            .filter(|v| self.s2_message_versions.iter().any(|ours| ours.matches(v)))
            .cloned()
            .collect::<Vec<_>>();
        if common.is_empty() && !request.force_pairing {
            return Err(refused(E::IncompatibleS2MessageVersions));
        }
        if request.node_id.is_some() && request.node_id_alias.is_some() {
            return Err(refused(E::ParsingError));
        }

        let client_challenge = super::base64_decode(&request.client_hmac_challenge)
            .ok_or_else(|| refused(E::ParsingError))?;
        // `R_c`: prove to the client that we hold the token and are the identity it
        // reached.
        let client_response = ChallengeResponse::compute(&client_challenge, token, &self.binding)?;
        // `C_s` / the response we will expect back in step 6.
        let expected_response = ChallengeResponse::compute(server_challenge, token, &self.binding)?;

        let accepted = PairingAccepted {
            pairing_attempt_id: attempt_id.clone(),
            server_node_description: self.local.clone(),
            server_endpoint_description: self.local_endpoint.clone(),
            selected_hmac_hashing_algorithm: HmacHashingAlgorithm::Sha256,
            client_hmac_challenge_response: client_response.as_base64(),
            server_hmac_challenge: super::base64_encode(server_challenge),
        };

        self.attempt = Some(Attempt {
            id: attempt_id,
            started: now,
            expected_response,
            client: request.client_node_description.clone(),
            client_endpoint: request.client_endpoint_description.clone(),
            s2_message_versions: common,
            details: None,
            verified: false,
        });
        let send_after = now.checked_add(MINIMUM_SERVER_DELAY).unwrap_or(now);
        self.pending = Some((send_after, accepted.clone()));
        Ok((send_after, accepted))
    }

    /// When the driver should next do something: the moment the delayed answer becomes
    /// sendable, or the moment the attempt's budget runs out.
    #[must_use]
    pub fn poll_timeout(&self) -> Option<Timestamp> {
        self.pending.as_ref().map(|(at, _)| *at).or_else(|| {
            self.attempt
                .as_ref()
                .map(|a| a.started.checked_add(PAIRING_BUDGET).unwrap_or(a.started))
        })
    }

    /// Take the delayed answer, if the mandatory second has elapsed.
    ///
    /// Returning `None` early is the point: a driver that loops on this cannot answer
    /// sooner than the specification allows, however tempting it is to.
    pub fn poll_response(&mut self, now: Timestamp) -> Option<PairingAccepted> {
        let (at, _) = self.pending.as_ref()?;
        if now < *at {
            return None;
        }
        self.pending.take().map(|(_, accepted)| accepted)
    }

    /// Authenticate a step-6-or-later request by its bearer.
    ///
    /// A `false` here is a `401`, and `S2C-OAS` says the client "may restart the pairing
    /// process by calling /requestPairing again" — so it must not fail the attempt.
    #[must_use]
    pub fn authenticates(&self, bearer: &str) -> bool {
        self.attempt.as_ref().is_some_and(|a| a.id.verify(bearer))
    }

    /// Steps 7A and 7B: check `serverHmacChallengeResponse`.
    ///
    /// A `false` here is a `403`: `S2C-OAS` — "The PairingAttempt has failed and cannot
    /// proceed", so the attempt is dropped rather than merely refused.
    pub fn verify_client(&mut self, response: &str, now: Timestamp) -> Result<(), ConnectError> {
        let Some(attempt) = self.attempt.as_mut() else {
            return Err(ConnectError::OutOfOrder {
                got: "a challenge response",
                expected: "the start of pairing",
            });
        };
        if now.saturating_duration_since(attempt.started) > PAIRING_BUDGET {
            self.fail(now);
            return Err(ConnectError::Expired {
                what: "pairing",
                limit: PAIRING_BUDGET,
            });
        }
        if !attempt.expected_response.verify(response) {
            self.fail(now);
            return Err(ConnectError::ChallengeFailed);
        }
        attempt.verified = true;
        Ok(())
    }

    /// Step 7A: what to answer `requestConnectionDetails` with, once verified.
    pub fn connection_details(
        &mut self,
        details: ConnectionDetails,
    ) -> Result<ConnectionDetails, ConnectError> {
        let attempt = self.attempt.as_mut().ok_or(ConnectError::OutOfOrder {
            got: "connection details",
            expected: "the start of pairing",
        })?;
        if !attempt.verified {
            return Err(ConnectError::ChallengeFailed);
        }
        attempt.details = Some(details.clone());
        Ok(details)
    }

    /// Step 7B: record the details the client posted, once verified.
    pub fn accept_connection_details(
        &mut self,
        details: ConnectionDetails,
    ) -> Result<(), ConnectError> {
        self.connection_details(details).map(|_| ())
    }

    /// Step 8: handle `finalizePairing`, yielding the pairing to store.
    ///
    /// A `success: false` is not an error — it is the client saying it could not proceed —
    /// but it yields no pairing.
    pub fn finalize(
        &mut self,
        body: FinalizePairing,
        now: Timestamp,
    ) -> Result<Option<Pairing>, ConnectError> {
        let Some(attempt) = self.attempt.take() else {
            return Err(ConnectError::OutOfOrder {
                got: "finalization",
                expected: "the start of pairing",
            });
        };
        self.last_finished = Some(now);
        self.pending = None;

        if now.saturating_duration_since(attempt.started) > PAIRING_BUDGET {
            return Err(ConnectError::Expired {
                what: "pairing",
                limit: PAIRING_BUDGET,
            });
        }
        if !body.success {
            return Ok(None);
        }
        if !attempt.verified {
            return Err(ConnectError::ChallengeFailed);
        }
        let details = attempt.details.ok_or(ConnectError::OutOfOrder {
            got: "finalization",
            expected: "connection details",
        })?;
        let client_deployment = attempt
            .client_endpoint
            .deployment
            .unwrap_or(Deployment::Lan);
        let own_deployment = self.local_endpoint.deployment.unwrap_or(Deployment::Lan);
        let (cem, rm) = if self.local.role == Role::Cem {
            (own_deployment, client_deployment)
        } else {
            (client_deployment, own_deployment)
        };
        Ok(Some(Pairing {
            local: self.local.id,
            remote: attempt.client,
            remote_endpoint: attempt.client_endpoint,
            details,
            communication_server: Deployment::communication_server(cem, rm),
            s2_message_versions: attempt.s2_message_versions,
        }))
    }

    fn fail(&mut self, now: Timestamp) {
        self.attempt = None;
        self.pending = None;
        self.last_finished = Some(now);
    }
}

fn refused(message: PairingErrorMessage) -> ConnectError {
    ConnectError::Refused(PairingRefused {
        error_message: message,
        additional_info: None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::connect::proto::{PairingCode, TokenKind};
    // Explicit because the crate is `no_std`: without `std` there is no prelude to take
    // `.to_string()` from, and `cargo test --lib --no-default-features` is a CI job.
    use alloc::string::ToString;

    const CLIENT_CHALLENGE: [u8; 32] = [0xA5; 32];
    const SERVER_CHALLENGE: [u8; 32] = [0x5A; 32];
    const ATTEMPT: [u8; 24] = [0x33; 24];

    fn binding() -> HmacBinding {
        HmacBinding::DomainName("pairing.example.com".to_string())
    }

    fn code() -> PairingCode {
        PairingCode::parse("evse7-A1b2C3", TokenKind::Static).expect("a legal code")
    }

    fn node(id: &str, role: Role) -> NodeDescription {
        NodeDescription {
            id: NodeId::parse(id).expect("a legal id"),
            brand: "Acme".to_string(),
            logo_url: None,
            kind: if role == Role::Cem { "CEM" } else { "EVSE" }.to_string(),
            model_name: "Charger 9000".to_string(),
            user_defined_name: None,
            role,
        }
    }

    fn endpoint(deployment: Deployment) -> EndpointDescription {
        EndpointDescription {
            name: Some("Test endpoint".to_string()),
            logo_url: None,
            deployment: Some(deployment),
        }
    }

    fn details() -> ConnectionDetails {
        ConnectionDetails {
            initiate_session_url: "https://pairing.example.com/v1/".to_string(),
            access_token: AccessToken::from_entropy(&[1u8; 32]).expect("32 bytes"),
            certificate_fingerprint: BTreeMap::new(),
        }
    }

    fn t(secs: i64) -> Timestamp {
        Timestamp::from_unix(1_700_000_000 + secs, 0)
    }

    fn attempt_id() -> PairingAttemptId {
        PairingAttemptId::from_entropy(&ATTEMPT).expect("24 bytes")
    }

    /// Both sides, driven end to end the way a real pairing runs: a WAN CEM as the
    /// pairing client, a LAN RM as the pairing server, so the RM is the pairing server
    /// and the CEM the communication server (6B).
    struct Run {
        client: PairingClient,
        server: PairingServer,
    }

    fn setup(
        client_role: Role,
        client_deployment: Deployment,
        server_deployment: Deployment,
    ) -> Run {
        Run {
            client: PairingClient::start(
                node("cem-1", client_role),
                endpoint(client_deployment),
                code(),
                t(0),
            ),
            server: PairingServer::new(
                node("rm-1", client_role.other()),
                endpoint(server_deployment),
                binding(),
            ),
        }
    }

    #[test]
    fn a_pairing_runs_to_completion_and_both_sides_agree() {
        let Run {
            mut client,
            mut server,
        } = setup(Role::Cem, Deployment::Lan, Deployment::Lan);

        // 1–3.
        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        let (send_after, accepted) = server
            .request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(0),
            )
            .unwrap();
        assert_eq!(send_after, t(1));
        let accepted = {
            assert!(server.poll_response(t(0)).is_none());
            server.poll_response(t(1)).unwrap_or(accepted)
        };

        // 4–5. Both LAN, so the CEM is the communication server: the client posts.
        let next = client
            .accept(accepted, binding(), Deployment::Lan, t(1))
            .unwrap();
        assert_eq!(next, NextStep::PostConnectionDetails);

        // 6B–7B.
        let post = client.post_connection_details(details(), t(1)).unwrap();
        assert!(server.authenticates(client.attempt_id().unwrap().as_str()));
        server
            .verify_client(&post.server_hmac_challenge_response, t(1))
            .unwrap();
        server
            .accept_connection_details(post.connection_details)
            .unwrap();

        // 8.
        let (body, mine) = client.finalize(t(2)).unwrap();
        assert!(body.success);
        let theirs = server.finalize(body, t(2)).unwrap().expect("a pairing");

        assert_eq!(client.step(), PairingStep::Paired);
        assert_eq!(mine.remote.id, theirs.local);
        assert_eq!(theirs.remote.id, mine.local);
        assert_eq!(mine.communication_server, Role::Cem);
        assert_eq!(theirs.communication_server, Role::Cem);
    }

    #[test]
    fn a_wan_pairing_server_supplies_the_details_instead() {
        // The RM is in the WAN, so it is the communication server and the client asks.
        let Run {
            mut client,
            mut server,
        } = setup(Role::Cem, Deployment::Lan, Deployment::Wan);

        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        let (_, accepted) = server
            .request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(0),
            )
            .unwrap();
        let next = client
            .accept(accepted, binding(), Deployment::Lan, t(1))
            .unwrap();
        assert_eq!(next, NextStep::RequestConnectionDetails);

        let ask = client.request_connection_details().unwrap();
        server
            .verify_client(&ask.server_hmac_challenge_response, t(1))
            .unwrap();
        let given = server.connection_details(details()).unwrap();
        client.connection_details(given, t(1)).unwrap();
        let (body, pairing) = client.finalize(t(2)).unwrap();
        assert_eq!(pairing.communication_server, Role::Rm);
        assert!(server.finalize(body, t(2)).unwrap().is_some());
    }

    #[test]
    fn the_response_may_not_be_sent_before_the_mandatory_second() {
        let Run {
            mut client,
            mut server,
        } = setup(Role::Cem, Deployment::Lan, Deployment::Lan);
        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        server
            .request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(0),
            )
            .unwrap();

        assert_eq!(server.poll_timeout(), Some(t(1)));
        assert!(server.poll_response(t(0)).is_none());
        assert!(
            server
                .poll_response(Timestamp::from_unix(1_700_000_000, 999_000_000))
                .is_none()
        );
        assert!(server.poll_response(t(1)).is_some());
        // And it is delivered once.
        assert!(server.poll_response(t(2)).is_none());
    }

    #[test]
    fn a_second_attempt_for_the_same_node_is_refused() {
        let Run {
            mut client,
            mut server,
        } = setup(Role::Cem, Deployment::Lan, Deployment::Lan);
        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        server
            .request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(0),
            )
            .unwrap();

        assert!(matches!(
            server.request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(1)
            ),
            Err(ConnectError::RateLimited)
        ));
        // Once its budget has run out, the slot frees.
        assert!(
            server
                .request_pairing(
                    &request,
                    &code().token,
                    &SERVER_CHALLENGE,
                    attempt_id(),
                    t(16)
                )
                .is_ok()
        );
    }

    #[test]
    fn a_wrong_token_costs_the_attacker_a_second_too() {
        let Run {
            mut client,
            mut server,
        } = setup(Role::Cem, Deployment::Lan, Deployment::Lan);
        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();

        // The server answers with *its* token; a client holding the wrong one fails in
        // step 4, not here — so the interesting failure is the reverse direction.
        let wrong = PairingToken::parse("Z9y8X7", TokenKind::Static).unwrap();
        let (_, accepted) = server
            .request_pairing(&request, &wrong, &SERVER_CHALLENGE, attempt_id(), t(0))
            .unwrap();
        assert!(matches!(
            client.accept(accepted, binding(), Deployment::Lan, t(1)),
            Err(ConnectError::ChallengeFailed)
        ));

        // And a client that guesses wrong at step 6 kills the attempt outright.
        let Run {
            mut client,
            mut server,
        } = setup(Role::Cem, Deployment::Lan, Deployment::Lan);
        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        let (_, accepted) = server
            .request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(0),
            )
            .unwrap();
        client
            .accept(accepted, binding(), Deployment::Lan, t(1))
            .unwrap();
        let forged = ChallengeResponse::compute(&SERVER_CHALLENGE, &wrong, &binding())
            .unwrap()
            .as_base64();
        assert!(matches!(
            server.verify_client(&forged, t(1)),
            Err(ConnectError::ChallengeFailed)
        ));
        // "The PairingAttempt has failed and cannot proceed."
        assert!(!server.authenticates(attempt_id().as_str()));
    }

    #[test]
    fn a_man_in_the_middle_cannot_relay_the_exchange() {
        // The attacker terminates TLS with his own certificate, so his binding differs.
        let attacker = HmacBinding::DomainName("pairing.example.com.evil.test".to_string());
        let mut client = PairingClient::start(
            node("cem-1", Role::Cem),
            endpoint(Deployment::Lan),
            code(),
            t(0),
        );
        let mut server =
            PairingServer::new(node("rm-1", Role::Rm), endpoint(Deployment::Lan), attacker);

        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        // He can relay the request and compute a response — but under his own name.
        let (_, accepted) = server
            .request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(0),
            )
            .unwrap();
        // The client, which binds to the name it *believes* it reached, refuses it.
        assert!(matches!(
            client.accept(accepted, binding(), Deployment::Lan, t(1)),
            Err(ConnectError::ChallengeFailed)
        ));
        assert_eq!(client.step(), PairingStep::Failed);
    }

    #[test]
    fn the_fifteen_second_budget_is_enforced_on_both_sides() {
        let Run {
            mut client,
            mut server,
        } = setup(Role::Cem, Deployment::Lan, Deployment::Lan);
        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        let (_, accepted) = server
            .request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(0),
            )
            .unwrap();

        assert!(matches!(
            client.accept(accepted, binding(), Deployment::Lan, t(16)),
            Err(ConnectError::Expired { .. })
        ));
        assert!(matches!(
            server.verify_client("anything", t(16)),
            Err(ConnectError::Expired { .. })
        ));
    }

    #[test]
    fn the_steps_cannot_be_taken_out_of_order() {
        let Run { mut client, .. } = setup(Role::Cem, Deployment::Lan, Deployment::Lan);
        assert!(matches!(
            client.finalize(t(0)),
            Err(ConnectError::OutOfOrder { .. })
        ));
        // And the attempt is now dead, not merely unhappy.
        assert_eq!(client.step(), PairingStep::Failed);
        assert!(client.request_pairing(&CLIENT_CHALLENGE).is_err());
    }

    #[test]
    fn two_nodes_of_the_same_role_are_refused_by_both_sides() {
        // The server refuses in step 1, with the enumerated reason.
        let mut client = PairingClient::start(
            node("cem-1", Role::Cem),
            endpoint(Deployment::Lan),
            code(),
            t(0),
        );
        let mut server = PairingServer::new(
            node("cem-2", Role::Cem),
            endpoint(Deployment::Lan),
            binding(),
        );
        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        let err = server
            .request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(0),
            )
            .unwrap_err();
        assert!(matches!(
            err,
            ConnectError::Refused(PairingRefused {
                error_message: PairingErrorMessage::InvalidCombinationOfRoles,
                ..
            })
        ));
    }

    #[test]
    fn incompatible_versions_are_refused_unless_forced() {
        let mut client = PairingClient::start(
            node("cem-1", Role::Cem),
            endpoint(Deployment::Lan),
            code(),
            t(0),
        )
        .with_s2_message_versions(alloc::vec![crate::types::ProtocolVersion::new("9.9.9")]);
        let mut server =
            PairingServer::new(node("rm-1", Role::Rm), endpoint(Deployment::Lan), binding());
        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        assert!(matches!(
            server.request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(0)
            ),
            Err(ConnectError::Refused(PairingRefused {
                error_message: PairingErrorMessage::IncompatibleS2MessageVersions,
                ..
            }))
        ));

        // Forced, it pairs anyway — the nodes cannot talk until one is updated, which is
        // what the flag is for.
        let mut client = PairingClient::start(
            node("cem-1", Role::Cem),
            endpoint(Deployment::Lan),
            code(),
            t(0),
        )
        .with_s2_message_versions(alloc::vec![crate::types::ProtocolVersion::new("9.9.9")])
        .forcing();
        let mut server =
            PairingServer::new(node("rm-1", Role::Rm), endpoint(Deployment::Lan), binding());
        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        assert!(
            server
                .request_pairing(
                    &request,
                    &code().token,
                    &SERVER_CHALLENGE,
                    attempt_id(),
                    t(16)
                )
                .is_ok()
        );
    }

    #[test]
    fn a_client_without_sha256_is_refused() {
        let Run {
            mut client,
            mut server,
        } = setup(Role::Cem, Deployment::Lan, Deployment::Lan);
        let mut request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        request.supported_hmac_hashing_algorithms.clear();
        assert!(matches!(
            server.request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(0)
            ),
            Err(ConnectError::Refused(PairingRefused {
                error_message: PairingErrorMessage::IncompatibleHmacHashingAlgorithms,
                ..
            }))
        ));
    }

    #[test]
    fn a_short_challenge_never_reaches_the_wire() {
        let Run { mut client, .. } = setup(Role::Cem, Deployment::Lan, Deployment::Lan);
        assert!(matches!(
            client.request_pairing(&[0u8; 16]),
            Err(ConnectError::WeakSecret { need: 32, .. })
        ));
    }

    #[test]
    fn the_attempt_id_is_a_bearer_and_is_compared_in_constant_time() {
        let Run {
            mut client,
            mut server,
        } = setup(Role::Cem, Deployment::Lan, Deployment::Lan);
        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        server
            .request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(0),
            )
            .unwrap();

        assert!(server.authenticates(attempt_id().as_str()));
        assert!(!server.authenticates("something else entirely"));
        assert!(!server.authenticates(""));
        // 24 bytes Base64-encode to the 32 characters the specification requires.
        assert_eq!(attempt_id().as_str().len(), PairingAttemptId::MIN_LEN);
        assert!(PairingAttemptId::from_entropy(&[0u8; 23]).is_err());
        // And it never prints itself.
        assert_eq!(
            alloc::format!("{:?}", attempt_id()),
            "PairingAttemptId(<redacted>)"
        );
    }

    #[test]
    fn a_client_that_gives_up_says_so_and_no_pairing_is_stored() {
        let Run {
            mut client,
            mut server,
        } = setup(Role::Cem, Deployment::Lan, Deployment::Lan);
        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        let (_, accepted) = server
            .request_pairing(
                &request,
                &code().token,
                &SERVER_CHALLENGE,
                attempt_id(),
                t(0),
            )
            .unwrap();
        client
            .accept(accepted, binding(), Deployment::Lan, t(1))
            .unwrap();

        let body = client.abandon();
        assert!(!body.success);
        assert!(server.finalize(body, t(2)).unwrap().is_none());
    }

    #[test]
    fn the_request_body_is_the_shape_the_openapi_defines() {
        let Run { mut client, .. } = setup(Role::Cem, Deployment::Lan, Deployment::Lan);
        let request = client.request_pairing(&CLIENT_CHALLENGE).unwrap();
        let json = serde_json::to_value(&request).expect("serializable");
        for key in [
            "clientNodeDescription",
            "clientEndpointDescription",
            "supportedCommunicationProtocols",
            "supportedS2MessageVersions",
            "supportedHmacHashingAlgorithms",
            "clientHmacChallenge",
        ] {
            assert!(json.get(key).is_some(), "missing required property {key}");
        }
        // "may never be used at the same time" — and `forcePairing` defaults to absent.
        assert!(json.get("nodeId").is_none());
        assert!(json.get("nodeIdAlias").is_some());
        assert!(json.get("forcePairing").is_none());
        assert_eq!(
            json["clientNodeDescription"]["role"].as_str(),
            Some("CEM"),
            "the role enum is spelled as the schema spells it"
        );
    }
}
