// @generated by `cargo xtask gen-schema-table` from schema/s2-json — do not edit.
//
// The property table of S2 JSON v1.0.0: every object type, its properties in
// schema order, which are required, and the bounds on every array. It is what
// lets the lenient decoder prune unknown properties and the validator check
// cardinality without anyone transcribing a number by hand.

use super::{ArrayBounds, Kind, Property, TypeSpec};

/// Every object type in S2 JSON v1.0.0, sorted by name.
///
/// One line per property, which is how a human reads a table; rustfmt would
/// explode each of the 550 entries across five lines and make it unreadable,
/// so it is asked not to.
#[rustfmt::skip]
pub static TYPES: &[TypeSpec] = &[
    TypeSpec {
        name: "DDBC.ActuatorDescription",
        message_type: None,
        properties: &[
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "diagnostic_label", required: false, kind: Kind::Scalar },
            Property { name: "supported_commodites", required: true, kind: Kind::ScalarArray(ArrayBounds { min: Some(1), max: Some(4) }) },
            Property { name: "operation_modes", required: true, kind: Kind::ObjectArray("DDBC.OperationMode", ArrayBounds { min: Some(1), max: Some(100) }) },
            Property { name: "transitions", required: true, kind: Kind::ObjectArray("Transition", ArrayBounds { min: Some(0), max: Some(1000) }) },
            Property { name: "timers", required: true, kind: Kind::ObjectArray("Timer", ArrayBounds { min: Some(0), max: Some(1000) }) },
        ],
    },
    TypeSpec {
        name: "DDBC.ActuatorStatus",
        message_type: Some("DDBC.ActuatorStatus"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "actuator_id", required: true, kind: Kind::Id },
            Property { name: "active_operation_mode_id", required: true, kind: Kind::Id },
            Property { name: "operation_mode_factor", required: true, kind: Kind::Scalar },
            Property { name: "previous_operation_mode_id", required: false, kind: Kind::Id },
            Property { name: "transition_timestamp", required: false, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "DDBC.AverageDemandRateForecast",
        message_type: Some("DDBC.AverageDemandRateForecast"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "start_time", required: true, kind: Kind::Scalar },
            Property { name: "elements", required: true, kind: Kind::ObjectArray("DDBC.AverageDemandRateForecastElement", ArrayBounds { min: Some(1), max: Some(288) }) },
        ],
    },
    TypeSpec {
        name: "DDBC.AverageDemandRateForecastElement",
        message_type: None,
        properties: &[
            Property { name: "duration", required: true, kind: Kind::Scalar },
            Property { name: "demand_rate_upper_limit", required: false, kind: Kind::Scalar },
            Property { name: "demand_rate_upper_95PPR", required: false, kind: Kind::Scalar },
            Property { name: "demand_rate_upper_68PPR", required: false, kind: Kind::Scalar },
            Property { name: "demand_rate_expected", required: true, kind: Kind::Scalar },
            Property { name: "demand_rate_lower_68PPR", required: false, kind: Kind::Scalar },
            Property { name: "demand_rate_lower_95PPR", required: false, kind: Kind::Scalar },
            Property { name: "demand_rate_lower_limit", required: false, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "DDBC.Instruction",
        message_type: Some("DDBC.Instruction"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "execution_time", required: true, kind: Kind::Scalar },
            Property { name: "abnormal_condition", required: true, kind: Kind::Scalar },
            Property { name: "actuator_id", required: true, kind: Kind::Id },
            Property { name: "operation_mode_id", required: true, kind: Kind::Id },
            Property { name: "operation_mode_factor", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "DDBC.OperationMode",
        message_type: None,
        properties: &[
            Property { name: "Id", required: true, kind: Kind::Id },
            Property { name: "diagnostic_label", required: false, kind: Kind::Scalar },
            Property { name: "power_ranges", required: true, kind: Kind::ObjectArray("PowerRange", ArrayBounds { min: Some(1), max: Some(10) }) },
            Property { name: "supply_range", required: true, kind: Kind::Object("NumberRange") },
            Property { name: "running_costs", required: false, kind: Kind::Object("NumberRange") },
            Property { name: "abnormal_condition_only", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "DDBC.PresentDemandStatus",
        message_type: Some("DDBC.PresentDemandStatus"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "present_demand_rate", required: true, kind: Kind::Object("NumberRange") },
        ],
    },
    TypeSpec {
        name: "DDBC.SystemDescription",
        message_type: Some("DDBC.SystemDescription"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "valid_from", required: true, kind: Kind::Scalar },
            Property { name: "actuators", required: true, kind: Kind::ObjectArray("DDBC.ActuatorDescription", ArrayBounds { min: Some(1), max: Some(10) }) },
            Property { name: "provides_average_demand_rate_forecast", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "DDBC.TimerStatus",
        message_type: Some("DDBC.TimerStatus"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "timer_id", required: true, kind: Kind::Id },
            Property { name: "actuator_id", required: true, kind: Kind::Id },
            Property { name: "finished_at", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "FRBC.ActuatorDescription",
        message_type: None,
        properties: &[
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "diagnostic_label", required: false, kind: Kind::Scalar },
            Property { name: "supported_commodities", required: true, kind: Kind::ScalarArray(ArrayBounds { min: Some(1), max: Some(4) }) },
            Property { name: "operation_modes", required: true, kind: Kind::ObjectArray("FRBC.OperationMode", ArrayBounds { min: Some(1), max: Some(100) }) },
            Property { name: "transitions", required: true, kind: Kind::ObjectArray("Transition", ArrayBounds { min: Some(0), max: Some(1000) }) },
            Property { name: "timers", required: true, kind: Kind::ObjectArray("Timer", ArrayBounds { min: Some(0), max: Some(1000) }) },
        ],
    },
    TypeSpec {
        name: "FRBC.ActuatorStatus",
        message_type: Some("FRBC.ActuatorStatus"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "actuator_id", required: true, kind: Kind::Id },
            Property { name: "active_operation_mode_id", required: true, kind: Kind::Id },
            Property { name: "operation_mode_factor", required: true, kind: Kind::Scalar },
            Property { name: "previous_operation_mode_id", required: false, kind: Kind::Id },
            Property { name: "transition_timestamp", required: false, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "FRBC.FillLevelTargetProfile",
        message_type: Some("FRBC.FillLevelTargetProfile"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "start_time", required: true, kind: Kind::Scalar },
            Property { name: "elements", required: true, kind: Kind::ObjectArray("FRBC.FillLevelTargetProfileElement", ArrayBounds { min: Some(1), max: Some(288) }) },
        ],
    },
    TypeSpec {
        name: "FRBC.FillLevelTargetProfileElement",
        message_type: None,
        properties: &[
            Property { name: "duration", required: true, kind: Kind::Scalar },
            Property { name: "fill_level_range", required: true, kind: Kind::Object("NumberRange") },
        ],
    },
    TypeSpec {
        name: "FRBC.Instruction",
        message_type: Some("FRBC.Instruction"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "actuator_id", required: true, kind: Kind::Id },
            Property { name: "operation_mode", required: true, kind: Kind::Id },
            Property { name: "operation_mode_factor", required: true, kind: Kind::Scalar },
            Property { name: "execution_time", required: true, kind: Kind::Scalar },
            Property { name: "abnormal_condition", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "FRBC.LeakageBehaviour",
        message_type: Some("FRBC.LeakageBehaviour"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "valid_from", required: true, kind: Kind::Scalar },
            Property { name: "elements", required: true, kind: Kind::ObjectArray("FRBC.LeakageBehaviourElement", ArrayBounds { min: Some(1), max: Some(288) }) },
        ],
    },
    TypeSpec {
        name: "FRBC.LeakageBehaviourElement",
        message_type: None,
        properties: &[
            Property { name: "fill_level_range", required: true, kind: Kind::Object("NumberRange") },
            Property { name: "leakage_rate", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "FRBC.OperationMode",
        message_type: None,
        properties: &[
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "diagnostic_label", required: false, kind: Kind::Scalar },
            Property { name: "elements", required: true, kind: Kind::ObjectArray("FRBC.OperationModeElement", ArrayBounds { min: Some(1), max: Some(100) }) },
            Property { name: "abnormal_condition_only", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "FRBC.OperationModeElement",
        message_type: None,
        properties: &[
            Property { name: "fill_level_range", required: true, kind: Kind::Object("NumberRange") },
            Property { name: "fill_rate", required: true, kind: Kind::Object("NumberRange") },
            Property { name: "power_ranges", required: true, kind: Kind::ObjectArray("PowerRange", ArrayBounds { min: Some(1), max: Some(10) }) },
            Property { name: "running_costs", required: false, kind: Kind::Object("NumberRange") },
        ],
    },
    TypeSpec {
        name: "FRBC.StorageDescription",
        message_type: None,
        properties: &[
            Property { name: "diagnostic_label", required: false, kind: Kind::Scalar },
            Property { name: "fill_level_label", required: false, kind: Kind::Scalar },
            Property { name: "provides_leakage_behaviour", required: true, kind: Kind::Scalar },
            Property { name: "provides_fill_level_target_profile", required: true, kind: Kind::Scalar },
            Property { name: "provides_usage_forecast", required: true, kind: Kind::Scalar },
            Property { name: "fill_level_range", required: true, kind: Kind::Object("NumberRange") },
        ],
    },
    TypeSpec {
        name: "FRBC.StorageStatus",
        message_type: Some("FRBC.StorageStatus"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "present_fill_level", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "FRBC.SystemDescription",
        message_type: Some("FRBC.SystemDescription"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "valid_from", required: true, kind: Kind::Scalar },
            Property { name: "actuators", required: true, kind: Kind::ObjectArray("FRBC.ActuatorDescription", ArrayBounds { min: Some(1), max: Some(10) }) },
            Property { name: "storage", required: true, kind: Kind::Object("FRBC.StorageDescription") },
        ],
    },
    TypeSpec {
        name: "FRBC.TimerStatus",
        message_type: Some("FRBC.TimerStatus"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "timer_id", required: true, kind: Kind::Id },
            Property { name: "actuator_id", required: true, kind: Kind::Id },
            Property { name: "finished_at", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "FRBC.UsageForecast",
        message_type: Some("FRBC.UsageForecast"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "start_time", required: true, kind: Kind::Scalar },
            Property { name: "elements", required: true, kind: Kind::ObjectArray("FRBC.UsageForecastElement", ArrayBounds { min: Some(1), max: Some(288) }) },
        ],
    },
    TypeSpec {
        name: "FRBC.UsageForecastElement",
        message_type: None,
        properties: &[
            Property { name: "duration", required: true, kind: Kind::Scalar },
            Property { name: "usage_rate_upper_limit", required: false, kind: Kind::Scalar },
            Property { name: "usage_rate_upper_95PPR", required: false, kind: Kind::Scalar },
            Property { name: "usage_rate_upper_68PPR", required: false, kind: Kind::Scalar },
            Property { name: "usage_rate_expected", required: true, kind: Kind::Scalar },
            Property { name: "usage_rate_lower_68PPR", required: false, kind: Kind::Scalar },
            Property { name: "usage_rate_lower_95PPR", required: false, kind: Kind::Scalar },
            Property { name: "usage_rate_lower_limit", required: false, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "Handshake",
        message_type: Some("Handshake"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "role", required: true, kind: Kind::Scalar },
            Property { name: "supported_protocol_versions", required: false, kind: Kind::ScalarArray(ArrayBounds { min: Some(1), max: None }) },
        ],
    },
    TypeSpec {
        name: "HandshakeResponse",
        message_type: Some("HandshakeResponse"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "selected_protocol_version", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "InstructionStatusUpdate",
        message_type: Some("InstructionStatusUpdate"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "instruction_id", required: true, kind: Kind::Id },
            Property { name: "status_type", required: true, kind: Kind::Scalar },
            Property { name: "timestamp", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "NumberRange",
        message_type: None,
        properties: &[
            Property { name: "start_of_range", required: true, kind: Kind::Scalar },
            Property { name: "end_of_range", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "OMBC.Instruction",
        message_type: Some("OMBC.Instruction"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "execution_time", required: true, kind: Kind::Scalar },
            Property { name: "operation_mode_id", required: true, kind: Kind::Id },
            Property { name: "operation_mode_factor", required: true, kind: Kind::Scalar },
            Property { name: "abnormal_condition", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "OMBC.OperationMode",
        message_type: None,
        properties: &[
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "diagnostic_label", required: false, kind: Kind::Scalar },
            Property { name: "power_ranges", required: true, kind: Kind::ObjectArray("PowerRange", ArrayBounds { min: Some(1), max: Some(10) }) },
            Property { name: "running_costs", required: false, kind: Kind::Object("NumberRange") },
            Property { name: "abnormal_condition_only", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "OMBC.Status",
        message_type: Some("OMBC.Status"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "active_operation_mode_id", required: true, kind: Kind::Id },
            Property { name: "operation_mode_factor", required: true, kind: Kind::Scalar },
            Property { name: "previous_operation_mode_id", required: false, kind: Kind::Id },
            Property { name: "transition_timestamp", required: false, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "OMBC.SystemDescription",
        message_type: Some("OMBC.SystemDescription"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "valid_from", required: true, kind: Kind::Scalar },
            Property { name: "operation_modes", required: true, kind: Kind::ObjectArray("OMBC.OperationMode", ArrayBounds { min: Some(1), max: Some(100) }) },
            Property { name: "transitions", required: true, kind: Kind::ObjectArray("Transition", ArrayBounds { min: Some(0), max: Some(1000) }) },
            Property { name: "timers", required: true, kind: Kind::ObjectArray("Timer", ArrayBounds { min: Some(0), max: Some(1000) }) },
        ],
    },
    TypeSpec {
        name: "OMBC.TimerStatus",
        message_type: Some("OMBC.TimerStatus"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "timer_id", required: true, kind: Kind::Id },
            Property { name: "finished_at", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "PEBC.AllowedLimitRange",
        message_type: None,
        properties: &[
            Property { name: "commodity_quantity", required: true, kind: Kind::Scalar },
            Property { name: "limit_type", required: true, kind: Kind::Scalar },
            Property { name: "range_boundary", required: true, kind: Kind::Object("NumberRange") },
            Property { name: "abnormal_condition_only", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "PEBC.EnergyConstraint",
        message_type: Some("PEBC.EnergyConstraint"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "valid_from", required: true, kind: Kind::Scalar },
            Property { name: "valid_until", required: true, kind: Kind::Scalar },
            Property { name: "upper_average_power", required: true, kind: Kind::Scalar },
            Property { name: "lower_average_power", required: true, kind: Kind::Scalar },
            Property { name: "commodity_quantity", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "PEBC.Instruction",
        message_type: Some("PEBC.Instruction"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "execution_time", required: true, kind: Kind::Scalar },
            Property { name: "abnormal_condition", required: true, kind: Kind::Scalar },
            Property { name: "power_constraints_id", required: true, kind: Kind::Id },
            Property { name: "power_envelopes", required: true, kind: Kind::ObjectArray("PEBC.PowerEnvelope", ArrayBounds { min: Some(1), max: Some(10) }) },
        ],
    },
    TypeSpec {
        name: "PEBC.PowerConstraints",
        message_type: Some("PEBC.PowerConstraints"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "valid_from", required: true, kind: Kind::Scalar },
            Property { name: "valid_until", required: false, kind: Kind::Scalar },
            Property { name: "consequence_type", required: true, kind: Kind::Scalar },
            Property { name: "allowed_limit_ranges", required: true, kind: Kind::ObjectArray("PEBC.AllowedLimitRange", ArrayBounds { min: Some(2), max: Some(100) }) },
        ],
    },
    TypeSpec {
        name: "PEBC.PowerEnvelope",
        message_type: None,
        properties: &[
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "commodity_quantity", required: true, kind: Kind::Scalar },
            Property { name: "power_envelope_elements", required: true, kind: Kind::ObjectArray("PEBC.PowerEnvelopeElement", ArrayBounds { min: Some(1), max: Some(288) }) },
        ],
    },
    TypeSpec {
        name: "PEBC.PowerEnvelopeElement",
        message_type: None,
        properties: &[
            Property { name: "duration", required: true, kind: Kind::Scalar },
            Property { name: "upper_limit", required: true, kind: Kind::Scalar },
            Property { name: "lower_limit", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "PPBC.EndInterruptionInstruction",
        message_type: Some("PPBC.EndInterruptionInstruction"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "power_profile_id", required: true, kind: Kind::Id },
            Property { name: "sequence_container_id", required: true, kind: Kind::Id },
            Property { name: "power_sequence_id", required: true, kind: Kind::Id },
            Property { name: "execution_time", required: true, kind: Kind::Scalar },
            Property { name: "abnormal_condition", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "PPBC.PowerProfileDefinition",
        message_type: Some("PPBC.PowerProfileDefinition"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "start_time", required: true, kind: Kind::Scalar },
            Property { name: "end_time", required: true, kind: Kind::Scalar },
            Property { name: "power_sequences_containers", required: true, kind: Kind::ObjectArray("PPBC.PowerSequenceContainer", ArrayBounds { min: Some(1), max: Some(1000) }) },
        ],
    },
    TypeSpec {
        name: "PPBC.PowerProfileStatus",
        message_type: Some("PPBC.PowerProfileStatus"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "sequence_container_status", required: true, kind: Kind::ObjectArray("PPBC.PowerSequenceContainerStatus", ArrayBounds { min: Some(1), max: Some(1000) }) },
        ],
    },
    TypeSpec {
        name: "PPBC.PowerSequence",
        message_type: None,
        properties: &[
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "elements", required: true, kind: Kind::ObjectArray("PPBC.PowerSequenceElement", ArrayBounds { min: Some(1), max: Some(288) }) },
            Property { name: "is_interruptible", required: true, kind: Kind::Scalar },
            Property { name: "max_pause_before", required: false, kind: Kind::Scalar },
            Property { name: "abnormal_condition_only", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "PPBC.PowerSequenceContainer",
        message_type: None,
        properties: &[
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "power_sequences", required: true, kind: Kind::ObjectArray("PPBC.PowerSequence", ArrayBounds { min: Some(1), max: Some(288) }) },
        ],
    },
    TypeSpec {
        name: "PPBC.PowerSequenceContainerStatus",
        message_type: None,
        properties: &[
            Property { name: "power_profile_id", required: true, kind: Kind::Id },
            Property { name: "sequence_container_id", required: true, kind: Kind::Id },
            Property { name: "selected_sequence_id", required: false, kind: Kind::Id },
            Property { name: "progress", required: false, kind: Kind::Scalar },
            Property { name: "status", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "PPBC.PowerSequenceElement",
        message_type: None,
        properties: &[
            Property { name: "duration", required: true, kind: Kind::Scalar },
            Property { name: "power_values", required: true, kind: Kind::ObjectArray("PowerForecastValue", ArrayBounds { min: Some(1), max: Some(10) }) },
        ],
    },
    TypeSpec {
        name: "PPBC.ScheduleInstruction",
        message_type: Some("PPBC.ScheduleInstruction"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "power_profile_id", required: true, kind: Kind::Id },
            Property { name: "sequence_container_id", required: true, kind: Kind::Id },
            Property { name: "power_sequence_id", required: true, kind: Kind::Id },
            Property { name: "execution_time", required: true, kind: Kind::Scalar },
            Property { name: "abnormal_condition", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "PPBC.StartInterruptionInstruction",
        message_type: Some("PPBC.StartInterruptionInstruction"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "power_profile_id", required: true, kind: Kind::Id },
            Property { name: "sequence_container_id", required: true, kind: Kind::Id },
            Property { name: "power_sequence_id", required: true, kind: Kind::Id },
            Property { name: "execution_time", required: true, kind: Kind::Scalar },
            Property { name: "abnormal_condition", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "PowerForecast",
        message_type: Some("PowerForecast"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "start_time", required: true, kind: Kind::Scalar },
            Property { name: "elements", required: true, kind: Kind::ObjectArray("PowerForecastElement", ArrayBounds { min: Some(1), max: Some(288) }) },
        ],
    },
    TypeSpec {
        name: "PowerForecastElement",
        message_type: None,
        properties: &[
            Property { name: "duration", required: true, kind: Kind::Scalar },
            Property { name: "power_values", required: true, kind: Kind::ObjectArray("PowerForecastValue", ArrayBounds { min: Some(1), max: Some(10) }) },
        ],
    },
    TypeSpec {
        name: "PowerForecastValue",
        message_type: None,
        properties: &[
            Property { name: "value_upper_limit", required: false, kind: Kind::Scalar },
            Property { name: "value_upper_95PPR", required: false, kind: Kind::Scalar },
            Property { name: "value_upper_68PPR", required: false, kind: Kind::Scalar },
            Property { name: "value_expected", required: true, kind: Kind::Scalar },
            Property { name: "value_lower_68PPR", required: false, kind: Kind::Scalar },
            Property { name: "value_lower_95PPR", required: false, kind: Kind::Scalar },
            Property { name: "value_lower_limit", required: false, kind: Kind::Scalar },
            Property { name: "commodity_quantity", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "PowerMeasurement",
        message_type: Some("PowerMeasurement"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "measurement_timestamp", required: true, kind: Kind::Scalar },
            Property { name: "values", required: true, kind: Kind::ObjectArray("PowerValue", ArrayBounds { min: Some(1), max: Some(10) }) },
        ],
    },
    TypeSpec {
        name: "PowerRange",
        message_type: None,
        properties: &[
            Property { name: "start_of_range", required: true, kind: Kind::Scalar },
            Property { name: "end_of_range", required: true, kind: Kind::Scalar },
            Property { name: "commodity_quantity", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "PowerValue",
        message_type: None,
        properties: &[
            Property { name: "commodity_quantity", required: true, kind: Kind::Scalar },
            Property { name: "value", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "ReceptionStatus",
        message_type: Some("ReceptionStatus"),
        properties: &[
            Property { name: "subject_message_id", required: true, kind: Kind::Id },
            Property { name: "status", required: true, kind: Kind::Scalar },
            Property { name: "diagnostic_label", required: false, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "ResourceManagerDetails",
        message_type: Some("ResourceManagerDetails"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "resource_id", required: true, kind: Kind::Id },
            Property { name: "name", required: false, kind: Kind::Scalar },
            Property { name: "roles", required: true, kind: Kind::ObjectArray("Role", ArrayBounds { min: Some(1), max: Some(3) }) },
            Property { name: "manufacturer", required: false, kind: Kind::Scalar },
            Property { name: "model", required: false, kind: Kind::Scalar },
            Property { name: "serial_number", required: false, kind: Kind::Scalar },
            Property { name: "firmware_version", required: false, kind: Kind::Scalar },
            Property { name: "instruction_processing_delay", required: true, kind: Kind::Scalar },
            Property { name: "available_control_types", required: true, kind: Kind::ScalarArray(ArrayBounds { min: Some(1), max: Some(5) }) },
            Property { name: "currency", required: false, kind: Kind::Scalar },
            Property { name: "provides_forecast", required: true, kind: Kind::Scalar },
            Property { name: "provides_power_measurement_types", required: true, kind: Kind::ScalarArray(ArrayBounds { min: Some(1), max: Some(10) }) },
        ],
    },
    TypeSpec {
        name: "RevokeObject",
        message_type: Some("RevokeObject"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "object_type", required: true, kind: Kind::Scalar },
            Property { name: "object_id", required: true, kind: Kind::Id },
        ],
    },
    TypeSpec {
        name: "Role",
        message_type: None,
        properties: &[
            Property { name: "role", required: true, kind: Kind::Scalar },
            Property { name: "commodity", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "SelectControlType",
        message_type: Some("SelectControlType"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "control_type", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "SessionRequest",
        message_type: Some("SessionRequest"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "request", required: true, kind: Kind::Scalar },
            Property { name: "diagnostic_label", required: false, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "Timer",
        message_type: None,
        properties: &[
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "diagnostic_label", required: false, kind: Kind::Scalar },
            Property { name: "duration", required: true, kind: Kind::Scalar },
        ],
    },
    TypeSpec {
        name: "Transition",
        message_type: None,
        properties: &[
            Property { name: "id", required: true, kind: Kind::Id },
            Property { name: "from", required: true, kind: Kind::Id },
            Property { name: "to", required: true, kind: Kind::Id },
            Property { name: "start_timers", required: true, kind: Kind::IdArray(ArrayBounds { min: Some(0), max: Some(1000) }) },
            Property { name: "blocking_timers", required: true, kind: Kind::IdArray(ArrayBounds { min: Some(0), max: Some(1000) }) },
            Property { name: "transition_costs", required: false, kind: Kind::Scalar },
            Property { name: "transition_duration", required: false, kind: Kind::Scalar },
            Property { name: "abnormal_condition_only", required: true, kind: Kind::Scalar },
        ],
    },
];

/// The object types whose shape differs in S2 JSON `v0.0.2-beta`, sorted by
/// name.
///
/// An overlay rather than a second full table: everything not listed here is
/// byte-identical between the two tags, and
/// [`type_spec_in`](super::type_spec_in) falls through to [`TYPES`].
#[rustfmt::skip]
pub static BETA_TYPES: &[TypeSpec] = &[
    TypeSpec {
        name: "DDBC.SystemDescription",
        message_type: Some("DDBC.SystemDescription"),
        properties: &[
            Property { name: "message_id", required: true, kind: Kind::Id },
            Property { name: "valid_from", required: true, kind: Kind::Scalar },
            Property { name: "actuators", required: true, kind: Kind::ObjectArray("DDBC.ActuatorDescription", ArrayBounds { min: Some(1), max: Some(10) }) },
            Property { name: "present_demand_rate", required: true, kind: Kind::Object("NumberRange") },
            Property { name: "provides_average_demand_rate_forecast", required: true, kind: Kind::Scalar },
        ],
    },
];
